# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            BD_STTP_2016
tagline:          'Big Data Short Term Training Programme 2016'
description:      'Some snippets used during the Big Data Short Term Training Programme 2016 at <a href="www.fcrit.ac.in/">F.C.R.I.T., Vashi</a>.'
#url:              https://github.com/user501254/
baseurl:          /BD_STTP_2016

author:
  name:           'Ashesh Kumar Singh'
  url:            https://user501254.github.io

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/user501254/BD_STTP_2016
  
plugins: [jekyll-paginate, jekyll-gist]
